### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by jwl317** [jwl317/2020thesis#1]
- [ ] Select a topic for my thesis

- [ ] Come up with a problem that I want to solve

- [ ] List up references
